# Generated by Django 4.1.6 on 2023-02-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('details', models.TextField(default='No description', max_length=3000, verbose_name='Подробное описание')),
                ('deadline', models.DateField(blank=True, max_length=16, null=True, verbose_name='Выполнить до')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in process', 'В процессе'), ('done', 'Сделано')], default='new', max_length=15, verbose_name='Статус')),
            ],
        ),
    ]
